version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-central-1:461902953491:task-definition/arda-demo:11"
        LoadBalancerInfo:
          ContainerName: "arda-demo"
          ContainerPort: 8080
        PlatformVersion: "LATEST"
