apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-01-29T17:17:48Z"
  generation: 7
  labels:
    app: nginx-1
  name: nginx-1
  namespace: default
  resourceVersion: "42373"
  selfLink: /apis/apps/v1/namespaces/default/deployments/nginx-1
  uid: d17b20a5-247c-42ee-81a1-a1bfce1facc2
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-1
    spec:
      containers:
        - image: gcr.io/deneme-232309/gjc:latest
          imagePullPolicy: Always
          name: gjc-1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2021-01-29T17:17:48Z"
      lastUpdateTime: "2021-01-29T17:18:35Z"
      message: ReplicaSet "nginx-1-98fc89d" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    - lastTransitionTime: "2021-01-29T19:47:50Z"
      lastUpdateTime: "2021-01-29T19:47:50Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
  observedGeneration: 7
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
